config:
  info: "config info for local(master)"

spring:
  application:
    name: ribbon-local-service

server:
  port: 8006

logging:
  level:
    root: info

user-service:
  name: user-local-service
